"""Characterization tests for the Domovoy wire format.

Domovoy (~/dev/domovoy) is the production client and MUST NOT require any
changes while the integration is refactored (see FABLE-AUDIT.md, "Hard
constraint"). These tests replay the exact payloads Domovoy puts on the
wire so the constraint is enforced by the suite instead of by prose.

The payloads below were generated by running Domovoy's own serialization
path (ServentsPlugin._create_entity: serde.to_dict +
strip_none_and_enums_from_containers) against servents-data-model 0.6.0.
Notable properties of the format:

- The nested device payload is sent under ``device_definition`` (the
  dataclass field name), NOT the legacy ``device_config`` key that
  services.yaml documents.
- ``app_name`` (entity and device) and ``is_global`` (device) are present.
  The integration ignores them; that is the decided behavior for now.
- All None-valued keys are stripped client-side.
"""

from unittest.mock import MagicMock, patch

import pytest
from servents.data_model.entity_configs import ClimateConfig, CoverConfig, DeviceConfig, FanConfig, LightConfig, SensorConfig

from custom_components.servents import handle_create_entity, handle_update_entity
from custom_components.servents.definitions import parse_entity_config
from custom_components.servents.sensor import ServEntSensor
from tests.conftest import FakeServiceCall


def domovoy_sensor_payload() -> dict:
    """Verbatim Domovoy create_entity payload for a plain sensor."""
    return {
        "entity_type": "sensor",
        "servent_id": "my_app-temperature",
        "name": "Temperature",
        "fixed_attributes": {},
        "disabled_by_default": False,
        "app_name": "my_app",
        "device_class": "temperature",
        "unit_of_measurement": "°C",
        "state_class": "measurement",
        "device_definition": {
            "device_id": "my_app",
            "name": "My App",
            "manufacturer": "apps.my_app/MyApp",
            "model": "my_app",
            "version": "Domovoy",
            "app_name": "my_app",
            "is_global": False,
        },
    }


def domovoy_light_payload() -> dict:
    """Verbatim Domovoy create_entity payload for a controllable light."""
    return {
        "entity_type": "light",
        "servent_id": "my_app-light",
        "name": "Light",
        "fixed_attributes": {},
        "disabled_by_default": False,
        "app_name": "my_app",
        "supports_brightness": True,
        "optimistic": True,
    }


def domovoy_cover_payload() -> dict:
    """Verbatim Domovoy create_entity payload for a controllable cover."""
    return {
        "entity_type": "cover",
        "servent_id": "my_app-cover",
        "name": "Cover",
        "fixed_attributes": {},
        "disabled_by_default": False,
        "app_name": "my_app",
        "device_class": "garage",
        "supports_position": True,
        "supports_stop": True,
        "optimistic": True,
    }


def domovoy_fan_payload() -> dict:
    """Verbatim Domovoy create_entity payload for a controllable fan."""
    return {
        "entity_type": "fan",
        "servent_id": "my_app-fan",
        "name": "Fan",
        "fixed_attributes": {},
        "disabled_by_default": False,
        "app_name": "my_app",
        "supports_percentage": True,
        "preset_modes": ["auto", "boost"],
        "optimistic": True,
    }


def domovoy_climate_payload() -> dict:
    """Verbatim Domovoy create_entity payload for a controllable climate."""
    return {
        "entity_type": "climate",
        "servent_id": "my_app-climate",
        "name": "Climate",
        "fixed_attributes": {},
        "disabled_by_default": False,
        "app_name": "my_app",
        "hvac_modes": ["off", "heat"],
        "supports_target_temperature": True,
        "supports_target_temperature_range": False,
        "min_temp": 15,
        "max_temp": 25,
        "temp_step": 0.5,
        "temperature_unit": "C",
        "optimistic": True,
        "default_state": "off",
    }


class TestDomovoyCreateEntity:
    async def create(self, registrar, payload=None):
        registrar.register_builder_for_definition(
            SensorConfig, lambda d: ServEntSensor(d), MagicMock()
        )
        await handle_create_entity(
            FakeServiceCall({"entities": [payload or domovoy_sensor_payload()]}, registrar)
        )
        return registrar.get_live_entity_for_servent_id("my_app-temperature")

    async def test_create_entity_succeeds(self, registrar):
        entity = await self.create(registrar)
        assert entity is not None
        assert entity._attr_name == "Temperature"
        assert entity._attr_native_unit_of_measurement == "°C"
        # servent_id must be published as an extra attribute: it is Domovoy's
        # only entity-discovery mechanism (get_entity_id_by_attribute).
        assert entity._attr_extra_state_attributes["servent_id"] == "my_app-temperature"

    async def test_app_name_and_is_global_are_silently_ignored(self, registrar):
        # Decided behavior (2026-07): the integration accepts and ignores
        # these Domovoy-only fields. They must never cause a rejection.
        # Since WP3 they are real fields on the shared model (parsed, not
        # dropped), but they still must not leak into published attributes.
        entity = await self.create(registrar)
        definition = registrar.get_all_definitions()[0]
        assert definition.app_name == "my_app"
        assert definition.device_definition.is_global is False
        assert "app_name" not in entity._attr_extra_state_attributes
        assert "is_global" not in entity._attr_extra_state_attributes

    async def test_device_definition_deserializes_to_device_config(self, registrar):
        # Fixed (FABLE-AUDIT H8, WP3): serde.from_dict deserializes the nested
        # device_definition dict into DeviceConfig natively at parse time —
        # no eager-coercion stopgap, no lazy getter.
        await self.create(registrar)
        definition = registrar.get_all_definitions()[0]
        assert isinstance(definition.device_definition, DeviceConfig)

    def test_device_info_property_returns_frozen_identifier(self):
        # The device- identifier prefix is frozen wire format for Domovoy.
        entity = ServEntSensor(parse_entity_config(domovoy_sensor_payload()))
        info = entity.device_info
        assert info["identifiers"] == {("servents", "device-my_app")}
        assert info["name"] == "My App"
        assert isinstance(entity.servent_config.device_definition, DeviceConfig)

    async def test_cleanup_devices_succeeds_on_domovoy_payload(self, registrar):
        # Fixed (FABLE-AUDIT H8, WP3): device_definition is a DeviceConfig from
        # parse time, so cleanup_devices works even when device_info was never
        # read (the original crash path for the Domovoy restart flow).
        from custom_components.servents.services import handle_cleanup_devices

        await self.create(registrar)
        assert isinstance(registrar.get_all_definitions()[0].device_definition, DeviceConfig)

        device_registry = MagicMock()
        device_registry.devices.values.return_value = []
        with patch("custom_components.servents.services.dr.async_get", return_value=device_registry):
            await handle_cleanup_devices(FakeServiceCall({}, registrar))

    async def test_recreate_from_domovoy_app_restart_updates_in_place(self, registrar):
        # Domovoy re-sends create_entity for every entity on app restart.
        # The second call must reconfigure the same live entity, not fail.
        entity = await self.create(registrar)
        renamed = domovoy_sensor_payload() | {"name": "Temperature v2"}
        await handle_create_entity(FakeServiceCall({"entities": [renamed]}, registrar))
        assert registrar.get_live_entity_for_servent_id("my_app-temperature") is entity
        assert entity._attr_name == "Temperature v2"


class TestDomovoyPhase6CreateEntity:
    @pytest.mark.parametrize(
        ("payload", "expected_class"),
        [
            (domovoy_light_payload(), LightConfig),
            (domovoy_cover_payload(), CoverConfig),
            (domovoy_fan_payload(), FanConfig),
        ],
    )
    def test_controllable_payloads_parse(self, payload, expected_class):
        definition = parse_entity_config(payload)

        assert type(definition) is expected_class
        assert definition.optimistic is True
        assert definition.app_name == "my_app"


class TestDomovoyPhase7CreateEntity:
    def test_climate_payload_parses(self):
        definition = parse_entity_config(domovoy_climate_payload())

        assert type(definition) is ClimateConfig
        assert definition.hvac_modes == ["off", "heat"]
        assert definition.supports_target_temperature is True
        assert definition.supports_target_temperature_range is False
        assert definition.default_state == "off"


class TestDomovoyUpdateState:
    async def test_update_state_payload(self, registrar):
        # Verbatim shape of ServEntEntity.set_to -> services.servents.update_state.
        live = MagicMock()
        registrar.register_live_entity("my_app-temperature", live)

        await handle_update_entity(
            FakeServiceCall(
                {"servent_id": "my_app-temperature", "state": 21.5, "attributes": {}}, registrar
            )
        )
        live.set_new_state_and_attributes.assert_called_once_with(21.5, {})
        live.verified_schedule_update_ha_state.assert_called_once()

    async def test_update_state_on_button_applies_attributes(self, registrar):
        # Constraint 3 / M2 (WP6): Domovoy exposes set_to on buttons; the call
        # must keep succeeding. It is no longer a silent no-op — the button now
        # applies the merged attributes (a button has no native value, so state
        # is ignored) and never raises. servent_id must stay present.
        from servents.data_model.entity_configs import ButtonConfig

        from custom_components.servents.button import ServEntButton

        button = ServEntButton(
            parse_entity_config(
                {"entity_type": "button", "servent_id": "b1", "name": "B", "event": "pressed"}
            ),
            MagicMock(),
        )
        assert isinstance(button.servent_config, ButtonConfig)
        registrar.register_live_entity("b1", button)

        await handle_update_entity(
            FakeServiceCall({"servent_id": "b1", "state": "anything", "attributes": {"note": "hi"}}, registrar)
        )
        # No exception; buttons have no native value to set.
        assert not hasattr(button, "_attr_native_value")
        # The attributes ARE applied, and servent_id is always present.
        assert button._attr_extra_state_attributes == {"note": "hi", "servent_id": "b1"}
