"""Characterization tests for the Domovoy wire format.

Domovoy (~/dev/domovoy) is the production client and MUST NOT require any
changes while the integration is refactored (see FABLE-AUDIT.md, "Hard
constraint"). These tests replay the exact payloads Domovoy puts on the
wire so the constraint is enforced by the suite instead of by prose.

The payloads below were generated by running Domovoy's own serialization
path (ServentsPlugin._create_entity: serde.to_dict +
strip_none_and_enums_from_containers) against servents-data-model 0.6.0.
Notable properties of the format:

- The nested device payload is sent under ``device_definition`` (the
  dataclass field name), NOT the ``device_config`` key that services.yaml
  documents and to_dataclass coerces eagerly.
- ``app_name`` (entity and device) and ``is_global`` (device) are present.
  The integration ignores them; that is the decided behavior for now.
- All None-valued keys are stripped client-side.
"""

from unittest.mock import MagicMock, patch

import pytest

from custom_components.servents import handle_create_entity, handle_update_entity
from custom_components.servents.data_carriers import (
    ServentDeviceDefinition,
    ServentSensorDefinition,
    to_dataclass,
)
from custom_components.servents.sensor import ServEntSensor
from tests.conftest import FakeServiceCall


def domovoy_sensor_payload() -> dict:
    """Verbatim Domovoy create_entity payload for a plain sensor."""
    return {
        "entity_type": "sensor",
        "servent_id": "my_app-temperature",
        "name": "Temperature",
        "fixed_attributes": {},
        "disabled_by_default": False,
        "app_name": "my_app",
        "device_class": "temperature",
        "unit_of_measurement": "°C",
        "state_class": "measurement",
        "device_definition": {
            "device_id": "my_app",
            "name": "My App",
            "manufacturer": "apps.my_app/MyApp",
            "model": "my_app",
            "version": "Domovoy",
            "app_name": "my_app",
            "is_global": False,
        },
    }


class TestDomovoyCreateEntity:
    async def create(self, registrar, payload=None):
        registrar.register_builder_for_definition(
            ServentSensorDefinition, lambda d: ServEntSensor(d), MagicMock()
        )
        await handle_create_entity(FakeServiceCall({"entities": [payload or domovoy_sensor_payload()]}))
        return registrar.get_live_entity_for_servent_id("my_app-temperature")

    async def test_create_entity_succeeds(self, registrar):
        entity = await self.create(registrar)
        assert entity is not None
        assert entity._attr_name == "Temperature"
        assert entity._attr_native_unit_of_measurement == "°C"
        # servent_id must be published as an extra attribute: it is Domovoy's
        # only entity-discovery mechanism (get_entity_id_by_attribute).
        assert entity._attr_extra_state_attributes["servent_id"] == "my_app-temperature"

    async def test_app_name_and_is_global_are_silently_ignored(self, registrar):
        # Decided behavior (2026-07): the integration accepts and ignores
        # these Domovoy-only fields. They must never cause a rejection.
        entity = await self.create(registrar)
        definition = registrar.get_all_entities()[0]
        assert not hasattr(definition, "app_name")
        assert not hasattr(definition, "is_global")
        assert "app_name" not in entity._attr_extra_state_attributes

    async def test_device_definition_dict_is_not_coerced_eagerly(self, registrar):
        # Quirk (FABLE-AUDIT H8): only the device_config key is coerced in
        # to_dataclass; Domovoy's device_definition key lands as a raw dict.
        await self.create(registrar)
        definition = registrar.get_all_entities()[0]
        assert isinstance(definition.device_definition, dict)

    def test_device_info_property_coerces_lazily(self):
        # The dict is converted only when HA reads the device_info property.
        # The device- identifier prefix is frozen wire format for Domovoy.
        entity = ServEntSensor(to_dataclass(domovoy_sensor_payload()))
        info = entity.device_info
        assert info["identifiers"] == {("servents", "device-my_app")}
        assert info["name"] == "My App"
        assert isinstance(entity.servent_config.device_definition, ServentDeviceDefinition)

    async def test_cleanup_devices_crashes_on_uncoerced_device_definition(self, registrar):
        # Bug (FABLE-AUDIT H8): if device_info was never read (e.g. after the
        # re-create flow swaps a fresh definition into the live entity),
        # handle_cleanup_devices calls .get_device_id() on the raw dict and
        # raises. This pins the bug; the fix flips this test to "succeeds".
        from custom_components.servents import setup

        await self.create(registrar)
        assert isinstance(registrar.get_all_entities()[0].device_definition, dict)

        hass = MagicMock()
        setup(hass, MagicMock())
        cleanup = next(
            call.args[2]
            for call in hass.services.register.call_args_list
            if call.args[1] == "cleanup_devices"
        )

        device_registry = MagicMock()
        device_registry.devices.values.return_value = []
        with patch("custom_components.servents.dr.async_get", return_value=device_registry):
            with pytest.raises(AttributeError, match="get_device_id"):
                await cleanup(FakeServiceCall({}))

    async def test_recreate_from_domovoy_app_restart_updates_in_place(self, registrar):
        # Domovoy re-sends create_entity for every entity on app restart.
        # The second call must reconfigure the same live entity, not fail.
        entity = await self.create(registrar)
        renamed = domovoy_sensor_payload() | {"name": "Temperature v2"}
        await handle_create_entity(FakeServiceCall({"entities": [renamed]}))
        assert registrar.get_live_entity_for_servent_id("my_app-temperature") is entity
        assert entity._attr_name == "Temperature v2"


class TestDomovoyUpdateState:
    async def test_update_state_payload(self, registrar):
        # Verbatim shape of ServEntEntity.set_to -> services.servents.update_state.
        live = MagicMock()
        registrar.register_live_entity("my_app-temperature", live)

        await handle_update_entity(
            FakeServiceCall(
                {"servent_id": "my_app-temperature", "state": 21.5, "attributes": {}}
            )
        )
        live.set_new_state_and_attributes.assert_called_once_with(21.5, {})
        live.verified_schedule_update_ha_state.assert_called_once()

    async def test_update_state_on_button_is_accepted_as_noop(self, registrar):
        # Constraint 3: Domovoy exposes set_to on buttons; the call must keep
        # succeeding. Currently it is a silent no-op via the base-class hook.
        from custom_components.servents.button import ServEntButton
        from custom_components.servents.data_carriers import ServentButtonDefinition

        button = ServEntButton(
            to_dataclass(
                {"entity_type": "button", "servent_id": "b1", "name": "B", "event": "pressed"}
            ),
            MagicMock(),
        )
        assert isinstance(button.servent_config, ServentButtonDefinition)
        registrar.register_live_entity("b1", button)

        await handle_update_entity(
            FakeServiceCall({"servent_id": "b1", "state": "anything", "attributes": {}})
        )
        # No exception, no state: buttons have no state to set.
        assert not hasattr(button, "_attr_native_value")
