DOMAIN = "servents"
DOMAIN_DATA = "servents_data"
VERSION = "0.0.1"
CONF_NAME = "ServEnts - Service Defined Entities"


SERVENTS_CONFIG_ENTS = 'ents'
SERVENTS_CONFIG_SENSORS = 'sensors'
SERVENTS_CONFIG_BINARY_SENSORS = 'binary_sensors'

SERVENT_BINARY_SENSOR = 'binary_sensor'

SERVENT_DEVICE_ID = 'servent_device_id'
SERVENT_DEVICE_NAME = 'name'
SERVENT_ENTITY_CATEGORY = 'entity_category'
SERVENT_ATTRIBUTES = 'attributes'
SERVENT_NAME = 'name'
SERVENT_ID = 'servent_id'
SERVENT_DEVICE_CLASS = 'device_class'
SERVENT_UNIT_OF_MEASUREMENT = 'unit_of_measurement'
SERVENT_STATE_CLASS = 'state_class'
SERVENT_ENUM_OPTIONS = 'options'

SERVENT_ENTITY = 'entity'
SERVENT_DEVICE = 'device'
SERVENT_SENSOR = 'sensor'

SERVENTS_CONFIG_SWITCHES = 'switches'
SERVENT_SWITCH = 'switch'

SERVENT_DEVICE_MANUFACTURER = 'manufacturer'
SERVENT_DEVICE_MODEL = 'model'
SERVENT_DEVICE_VERSION = 'version'

SERVENT_ENTITY_DEFAULT_STATE = 'default_state'


SERVENT_NUMBER = 'number'
SERVENTS_CONFIG_NUMBERS = 'numbers'

SERVENT_NUMBER_STEP = 'step'
SERVENT_NUMBER_MODE = 'mode'
SERVENT_NUMBER_MAX_VALUE = 'max_value'
SERVENT_NUMBER_MIN_VALUE = 'min_value'

SERVENTS_CONFIG_SELECTS = 'selects'
SERVENT_SELECT = 'select'

SERVENTS_CONFIG_BUTTONS = 'buttons'
SERVENT_BUTTON = 'button'
SERVENT_BUTTON_EVENT = 'event'
SERVENT_BUTTON_EVENT_DATA = 'event_data'
